name: Build_UnitTest_Xcode
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test with Latest Xcode
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: TekkonCC Unit Test
        run: xcodebuild -scheme TekkonCCTests -configuration Debug test
